metricbeat.modules:
- module: docker
  # metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  metricsets: ["container", "cpu", "diskio", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

- module: system
  metricsets:
    # CPU stats
    - cpu

    # System Load stats
    - load

    # Per CPU core stats
    - core

    # IO stats
    - diskio

    # Per filesystem stats
    - filesystem

    # File system summary stats
    - fsstat

    # Memory stats
    - memory

    # Network stats
    - network

    # Per process stats
    - process

    # Sockets (linux only)
    #- socket
  enabled: true
  period: 10s
  processes: ['.*']
  cgroups: true  # Remove for versions >= 5.3

# In order to capture short lived connections, use a shorter period for system/sockets.
- module: system
  metricsets: [socket]
  period: 500ms
  socket.reverse_lookup.enabled: true

- module: system
  period: 60s
  metricsets: [filesystem, fsstat]
  filters:
    - drop_event.when.regexp.mount_point: '^(/hostfs)?/(sys|cgroup|proc|dev|etc|host|var/lib/docker)($|/)'

processors:
- add_cloud_metadata:

output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5044"]
  index: metrics

logging.level: info

logging.selectors: ["*"]
